elasticsearch:
  host: 192.168.211.132
  port: 9201


#datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.211.132:3306/es?serverTimeZone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatics
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.es.esdemo.pojo